project:
  type: website
  render:
    - "*.qmd"
    - "!21-genai/gemini.qmd"

website:
  favicon: assets/favicon.ico
  google-analytics: G-CES9J82GLL
  site-url: "https://data6.org/notes/"
  page-footer: 
    center:
      - text: Home / About / License
        href: index.qmd
      - text: GitHub
        href: "https://github.com/data-6-berkeley"
      - text: Accessibility
        href: "https://dap.berkeley.edu/get-help/report-web-accessibility-issue"
      - text: Nondiscrimination
        href: "https://ophd.berkeley.edu/policies-and-procedures/nondiscrimination-policy-statement"
    background: "dark"
  page-navigation: true
  sidebar:
    style: "docked"
    title: "DATA 6 <br><small>Course Notes</small>"
    logo: assets/data6.png
    logo-alt: "Data 6 logo"
    collapse-level: 1 # doesn't expand next level
    tools:
      - icon: github
        href: https://github.com/data-6-berkeley/notes
    contents:
      - href: index.qmd
        text: Home / About
      - section: "L01: Introduction"
        href: 01-intro/index.qmd
        contents:
          - href: 01-intro/index.qmd
            text: "Course Introduction"
          - href: 01-intro/jupyter-notebook.qmd
            text: Jupyter Notebooks
          - href: 01-intro/programming-basics.qmd
            text: Programming Basics
      - section: "L02: Data Types"
        href: 02-datatypes/index.qmd
        contents:
          - href: 02-datatypes/index.qmd
            text: "Numeric and String Data Types"
          - href: 02-datatypes/rates-incidence.qmd
            text: "Application: Rates and Incidence"
      - section: "L03: Arrays"
        href: 03-arrays/index.qmd
        contents:
          - href: 03-arrays/index.qmd
            text: "Arrays"
          - href: 03-arrays/numpy.qmd
            text: "NumPy and Array Functions"
      - section: "L04: Table Fundamentals"
        href: 04-tables/index.qmd
        contents:
          - href: 04-tables/index.qmd
            text: "Table Fundamentals"
          - href: 04-tables/exercises.qmd
            text: "Table Exercises"
          - href: 04-tables/none-print.qmd
            text: "None and Print"
      - section: "L05: Variables in Social Science"
        href: 05-variables/index.qmd
        contents:
          - href: 05-variables/index.qmd
            text: "Variables and Variable Types"
          - href: 05-variables/units-of-analysis.qmd
            text: "Units of Analysis"
      - section: "L06: Variables II"
        href: 06-variables-ii/index.qmd
        contents:
          - href: 06-variables-ii/index.qmd
            text: "Causality vs. EDA"
          - href: 06-variables-ii/sample-population.qmd
            text: "Sample vs. Population"
      - section: "L07: Visualizations"
        href: 07-visualizations/index.qmd
        contents:
          - href: 07-visualizations/index.qmd
            text: "Visualizations"
          - href: 07-visualizations/encoding.qmd
            text: "Encoding"
          - href: 07-visualizations/charts.qmd
            text: "Bar Charts, Scatter Plots, Line Graphs"
      - section: "L08: Histograms"
        href: 08-histograms/index.qmd
        contents:
          - href: 08-histograms/index.qmd
            text: "Histograms and Ranges"
          - href: 08-histograms/exercises.qmd
            text: "Exercises"
      - section: "L09: Summary Statistics and Box Plots"
        href: 09-summary-statistics/index.qmd
        contents:
          - href: 09-summary-statistics/index.qmd
            text: "Percentiles and Box Plots"
          - href: 09-summary-statistics/center-spread.qmd
            text: "Center and Spread"
      - section: "L10: Filtering and Boolean Predicates"
        href: 10-boolean-predicates/index.qmd
        contents:
          - href: 10-boolean-predicates/index.qmd
            text: "Filtering and Boolean Predicates"
          - href: 10-boolean-predicates/boolean.qmd
            text: "Booleans"
      - text: "L11: Grouping"
        href: 11-group/index.qmd
      - text: "L12: Pivots and Joins"
        href: 12-pivot-join/index.qmd
      - section: "L13: Functions"
        href: 13-functions/index.qmd
        contents:
          - href: 13-functions/index.qmd
            text: "Functions"
          - href: 13-functions/strings.qmd
            text: "String Methods"
          - href: 13-functions/apply.qmd
            text: "Apply"
      - text: "L14: Conditionals"
        href: 14-conditionals/index.qmd
      - text: "L15: Iteration"
        href: 15-iteration/index.qmd
        contents:
          - href: 15-iteration/index.qmd
            text: "For Loops"
          - href: 15-iteration/while.qmd
            text: "While Loops"
          - href: 15-iteration/practice.qmd
            text: "Practice"
      - text: "L16: Iterations II; Measurements"
        href: 16-measurements/index.qmd
        contents:
          - href: 16-measurements/index.qmd
            text: "Reliability and Validity"
          - href: 16-measurements/iteration-ii.qmd
            text: "More Iteration Practice"
      - text: "L17: Dictionaries"
        href: 17-dictionaries/index.qmd
        contents:
          - href: 17-dictionaries/index.qmd
            text: "Dictionaries"
          - href: 17-dictionaries/file-formats.qmd
            text: "File Formats"
      - text: "L18: HTML and Web Scraping"
        href: 18-html/index.qmd
        contents:
          - href: 18-html/index.qmd
            text: "HTML and BeautifulSoup"
          - href: 18-html/genius.qmd
            text: "Genius API Key"
      - text: "L19: Intro to Computational Social Science"
        href: 19-css/index.qmd
      - text: "L20: Qualitative Coding"
        href: 20-coding/index.qmd
        contents:
          - href: 20-coding/index.qmd
            text: "Qualitative Coding"
          - href: 20-coding/cohens-kappa.qmd
            text: "Cohen's Kappa"
      - text: "L21: Generative AI"
        href: 21-genai/index.qmd
        contents:
          - href: 21-genai/index.qmd
            text: "GenAI and LLMs"
          - href: 21-genai/gemini.qmd
            text: "Gemini Tutorial"
      - href: five-things.qmd
        text: "5 Things to Know"
      - href: reference.qmd
        text: "Data 6 Python Reference"

format:
  html:
    theme: lumen
    fontsize: 1em
    css: assets/styles.css
    toc: true
    include-in-header:
      file: siteimprove.html

